name: test
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
      - name: my-step
        run: |
           sudo apt update
           sudo apt install qemu-kvm -y
           wget -O win.iso "https://drive.massgrave.dev/en_windows_server_2019_x64_dvd_4cb967d8.iso"
           wget -O ngrok.tgz "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
           wget https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.zip
           unzip noVNC-1.4.0.zip
           chmod +x noVNC-1.4.0/utils/novnc_proxy
           tar -xf ngrok.tgz && chmod +x ngrok
           ./ngrok config add-authtoken 2eTzTtisRPj4pnUlPB0p8kGKdMR_5QHLfQkLt8qeaTwFDRnRP
           ./ngrok http --region ap 6080 &>/dev/null &
           curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
           ./noVNC-1.4.0/utils/novnc_proxy --vnc localhost:5901 --listen localhost:6081 &>/dev/null &
           qemu-img create -f qcow2 winl.img 64G
           qemu-system- -hda winl.img -m 6G -boot d -cdrom "win.iso" -smp cores=2 -cpu host -enable-kvm -vnc :0 -machine usb=on -device usb-tablet

           
           
